;;; nol-compilation-diagnosis-test.el --- Prototype tests -*- lexical-binding: t; -*-
(require 'ert)
(require 'cl-lib)
(require 'compile)
(require 'nol-compilation-diagnosis)
(require 'gptel)

(ert-deftest nol/compilation-diagnosis-hint-only-on-failure ()
  (with-temp-buffer
    (compilation-mode)
    (nol/compilation-diagnosis-finish (current-buffer) "finished\n")
    (should-not nol/compilation-diagnosis-failed)
    (nol/compilation-diagnosis-finish (current-buffer) "exited abnormally with code 1\n")
    (should nol/compilation-diagnosis-failed)
    (should (string-match-p "C-c C-d" (buffer-string)))
    (should (eq (lookup-key compilation-mode-map (kbd "C-c C-d"))
                #'nol/compilation-diagnose))))

(ert-deftest nol/compilation-diagnosis-tools-confined-to-root ()
  (let* ((root (make-temp-file "diag-root" t))
         (outside (make-temp-file "diag-outside" t))
         (file (expand-file-name "error.txt" root)))
    (unwind-protect
        (progn
          (with-temp-file file (insert "error text"))
          (with-temp-file (expand-file-name "secret" outside) (insert "secret"))
          (make-symbolic-link outside (expand-file-name "escape" root))
          (let* ((tools (nol/compilation-diagnosis-tools root))
                 (listing (gptel-tool-function (car tools)))
                 (reading (gptel-tool-function (cadr tools))))
            (should (string-match-p "error.txt" (funcall listing ".")))
            (should (string-match-p "error text" (funcall reading "error.txt")))
            (dolist (path '("../" "/etc" "escape" "escape/secret"))
              (should-error (funcall listing path)))
            (dolist (path '("../secret" "/etc/passwd" "escape/secret"))
              (should-error (funcall reading path)))))
      (delete-directory root t)
      (delete-directory outside t))))

(ert-deftest nol/compilation-diagnosis-starts-with-only-scoped-tools ()
  (let ((root (make-temp-file "diag-start" t))
        (chat nil) (sent nil))
    (unwind-protect
        (with-temp-buffer
          (compilation-mode)
          (setq default-directory (file-name-as-directory root))
          (let ((inhibit-read-only t)) (insert "make: *** failed\n"))
          (setq-local nol/compilation-diagnosis-failed t)
          (setq-local compilation-arguments '("actual-build"))
          (cl-letf (((symbol-function 'project-current) (lambda (&rest _) nil))
                    ((symbol-function 'gptel) (lambda (_name _key prompt)
                                                (setq chat (generate-new-buffer "*test-chat*"))
                                                (with-current-buffer chat (insert prompt))
                                                chat))
                    ((symbol-function 'gptel-send) (lambda ()
                                                     (setq sent (list (buffer-string) gptel-tools default-directory)))))
            (nol/compilation-diagnose)
            (should sent)
            (should (string-match-p "make: \\*\\*\\* failed" (car sent)))
            (should (string-match-p "Command: actual-build" (car sent)))
            (should (= (length (cadr sent)) 2))
            (should (equal (caddr sent) (file-name-as-directory root)))))
      (when (buffer-live-p chat) (kill-buffer chat))
      (delete-directory root t))))

(ert-deftest nol/compilation-diagnosis-real-gptel-buffer ()
  (require 'gptel-openai)
  (let ((root (make-temp-file "diag-real" t))
        (gptel-default-mode 'text-mode)
        (gptel-backend (gptel-make-openai "Test" :key "test" :models '(gpt-4o)))
        (gptel-model 'gpt-4o)
        (chat nil) (sent nil))
    (unwind-protect
        (with-temp-buffer
          (compilation-mode)
          (setq default-directory (file-name-as-directory root))
          (setq-local nol/compilation-diagnosis-failed t)
          (cl-letf (((symbol-function 'project-current) (lambda (&rest _) nil))
                    ((symbol-function 'gptel-send)
                     (lambda () (setq chat (current-buffer) sent gptel-tools))))
            (nol/compilation-diagnose)
            (should (buffer-live-p chat))
            (should (buffer-local-value 'gptel-mode chat))
            (should (= (length sent) 2))
            (should (eq (buffer-local-value 'gptel-use-tools chat) t))))
      (when (buffer-live-p chat) (kill-buffer chat))
      (delete-directory root t))))

(ert-deftest nol/compilation-diagnosis-real-failed-compilation ()
  (let* ((default-directory (make-temp-file "diag-compile" t))
         (buffer (compilation-start "false" 'compilation-mode
                                    (lambda (_) "*diag-compile-test*"))))
    (unwind-protect
        (progn
          (while (get-buffer-process buffer)
            (accept-process-output nil 0.1))
          (with-current-buffer buffer
            (should nol/compilation-diagnosis-failed)
            (should (string-match-p "C-c C-d" (buffer-string)))))
      (when (buffer-live-p buffer) (kill-buffer buffer))
      (delete-directory default-directory t))))

(provide 'nol-compilation-diagnosis-test)
